spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contactDB?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
    prefix: file:./src/main/resources/templates/
